"""Full sellable service definitions — complements platform_services.service_catalog."""

from __future__ import annotations

from typing import Any

_SERVICES: list[dict[str, Any]] = [
    {
        "service_id": "free_growth_diagnostic",
        "name_ar": "تشخيص نمو مجاني",
        "target_customer_ar": "أي شركة B2B",
        "outcome_ar": "٣ فرص + رسالة واحدة + تقرير مخاطر + اقتراح Pilot.",
        "inputs_required": ["company_name", "sector", "city", "offer"],
        "workflow_steps": ["intake", "analyze", "draft", "proof_preview", "upsell"],
        "deliverables_ar": ["٣ فرص", "١ رسالة", "١ تقرير مخاطر", "اقتراح خدمة مدفوعة"],
        "pricing_range_sar": {"min": 0, "max": 0},
        "risk_level": "low",
        "required_integrations": [],
        "approval_policy": "draft_only",
        "proof_metrics": ["diagnostic_to_paid_conversion"],
        "upgrade_path": "first_10_opportunities",
    },
    {
        "service_id": "list_intelligence",
        "name_ar": "ذكاء القوائم",
        "target_customer_ar": "شركات لديها CSV أرقام/إيميلات",
        "outcome_ar": "تطبيع، تصنيف مصدر، contactability، أفضل ٥٠ هدفاً، مسودات.",
        "inputs_required": ["csv_or_contacts", "sector"],
        "workflow_steps": [
            "intake",
            "data_check",
            "targeting",
            "contactability",
            "draft",
            "approve",
            "proof",
            "upsell",
        ],
        "deliverables_ar": ["تقرير القائمة", "أفضل ٥٠", "مسودات إيميل/مهمة", "تقرير مخاطر"],
        "pricing_range_sar": {"min": 499, "max": 1500},
        "risk_level": "medium",
        "required_integrations": [],
        "approval_policy": "approval_required_for_send",
        "proof_metrics": ["safe_ratio", "drafts_created", "blocked_count"],
        "upgrade_path": "growth_os",
    },
    {
        "service_id": "first_10_opportunities",
        "name_ar": "سباق ١٠ فرص",
        "target_customer_ar": "مؤسس أو فريق مبيعات يحتاج فرصاً سريعة",
        "outcome_ar": "١٠ فرص + لماذا الآن + رسائل عربية + خطة متابعة + Proof Pack.",
        "inputs_required": ["sector", "city", "offer", "goal"],
        "workflow_steps": [
            "intake",
            "analyze",
            "target",
            "draft",
            "approve",
            "track",
            "proof",
            "upsell",
        ],
        "deliverables_ar": ["١٠ فرص", "١٠ مسودات", "خطة متابعة", "قالب Proof Pack"],
        "pricing_range_sar": {"min": 499, "max": 1500},
        "risk_level": "medium",
        "required_integrations": [],
        "approval_policy": "approval_required_for_send",
        "proof_metrics": ["opportunities_count", "accept_rate", "meetings_booked"],
        "upgrade_path": "growth_os",
    },
    {
        "service_id": "self_growth_operator",
        "name_ar": "مشغّل نمو ذاتي",
        "target_customer_ar": "مؤسسون ومستشارون ووكالات صغيرة",
        "outcome_ar": "موجز يومي + كروت قرار + مسودات — بدون إرسال حي افتراضياً.",
        "inputs_required": ["goal", "channels"],
        "workflow_steps": ["intake", "analyze", "draft", "approve", "track", "proof", "upsell"],
        "deliverables_ar": ["Daily brief", "٥ كروت/يوم", "تقرير أسبوعي"],
        "pricing_range_sar": {"min": 999, "max": 1999},
        "risk_level": "low",
        "required_integrations": [],
        "approval_policy": "approval_required_for_send",
        "proof_metrics": ["cards_approved", "time_saved_hours"],
        "upgrade_path": "growth_os",
    },
    {
        "service_id": "growth_os",
        "name_ar": "Growth OS شهري",
        "target_customer_ar": "شركات B2B صغيرة ومتوسطة",
        "outcome_ar": "Targeting + قنوات + Proof Ledger + تسريبات إيراد.",
        "inputs_required": ["onboarding_profile", "channels"],
        "workflow_steps": [
            "intake",
            "data_check",
            "targeting",
            "contactability",
            "strategy",
            "drafting",
            "approval",
            "execution_or_export",
            "tracking",
            "proof",
            "upsell",
        ],
        "deliverables_ar": ["Command feed", "Proof Pack أسبوعي", "تقرير قنوات"],
        "pricing_range_sar": {"min": 2999, "max": 9999},
        "risk_level": "medium",
        "required_integrations": ["gmail", "google_calendar", "whatsapp", "moyasar"],
        "approval_policy": "approval_required_for_send",
        "proof_metrics": ["revenue_influenced_sar", "meetings_booked", "risks_blocked"],
        "upgrade_path": "agency_partner_program",
    },
    {
        "service_id": "partner_sprint",
        "name_ar": "سباق شراكات",
        "target_customer_ar": "شركات تريد توسعاً عبر شركاء",
        "outcome_ar": "فئات شركاء + أهداف + مسودات + اجتماعات مقترحة + مسودة اتفاق إحالة.",
        "inputs_required": ["partner_goal", "sector"],
        "workflow_steps": ["intake", "target", "draft", "approve", "track", "proof", "upsell"],
        "deliverables_ar": ["قائمة شركاء", "مسودات", "Partner scorecard", "مسودة اتفاق"],
        "pricing_range_sar": {"min": 3000, "max": 7500},
        "risk_level": "low",
        "required_integrations": [],
        "approval_policy": "approval_required_for_send",
        "proof_metrics": ["partner_meetings", "referral_pipeline"],
        "upgrade_path": "agency_partner_program",
    },
    {
        "service_id": "agency_partner_program",
        "name_ar": "برنامج شركاء وكالات",
        "target_customer_ar": "وكالات تسويق ومبيعات",
        "outcome_ar": "Onboarding وكالة + عميل تجريبي + Proof مشترك + revenue share outline.",
        "inputs_required": ["agency_profile"],
        "workflow_steps": ["intake", "analyze", "draft", "approve", "track", "proof"],
        "deliverables_ar": ["اتفاقية إطار draft", "قالب Proof مشترك", "SLA تشغيل"],
        "pricing_range_sar": {"min": 5000, "max": 25000},
        "risk_level": "medium",
        "required_integrations": [],
        "approval_policy": "legal_review_required",
        "proof_metrics": ["clients_onboarded", "revenue_share_estimate"],
        "upgrade_path": "growth_os",
    },
    {
        "service_id": "email_revenue_rescue",
        "name_ar": "إنقاذ إيراد البريد",
        "target_customer_ar": "شركات بريد مليء بفرص ضائعة",
        "outcome_ar": "كشف فرص متأخرة + مسودات Gmail فقط — بدون إرسال حتى موافقة.",
        "inputs_required": ["gmail_label_scope"],
        "workflow_steps": ["intake", "data_check", "draft", "approve", "proof", "upsell"],
        "deliverables_ar": ["تقرير فرص ضائعة", "مسودات متابعة", "اجتماعات مقترحة"],
        "pricing_range_sar": {"min": 1500, "max": 5000},
        "risk_level": "medium",
        "required_integrations": ["gmail"],
        "approval_policy": "approval_required_for_send",
        "proof_metrics": ["drafts_approved", "meetings_from_email"],
        "upgrade_path": "growth_os",
    },
    {
        "service_id": "whatsapp_compliance_setup",
        "name_ar": "إعداد واتساب بامتثال",
        "target_customer_ar": "شركات تستخدم واتساب بشكل عشوائي",
        "outcome_ar": "تدقيق قوائم + opt-in + منع بارد + قوالب موافقة.",
        "inputs_required": ["contact_sample_or_policy"],
        "workflow_steps": ["intake", "contactability", "draft", "approve", "proof"],
        "deliverables_ar": ["تقرير امتثال", "قوالب opt-in", "سياسة موافقات"],
        "pricing_range_sar": {"min": 1500, "max": 4000},
        "risk_level": "high",
        "required_integrations": ["whatsapp"],
        "approval_policy": "cold_blocked_default",
        "proof_metrics": ["blocked_cold_count", "opt_in_templates"],
        "upgrade_path": "growth_os",
    },
    {
        "service_id": "linkedin_lead_gen_setup",
        "name_ar": "إعداد LinkedIn Lead Gen",
        "target_customer_ar": "B2B يستهدف قرارين",
        "outcome_ar": "خطة Lead Forms + حقول مخفية + مسودات متابعة — بدون scraping.",
        "inputs_required": ["icp", "offer"],
        "workflow_steps": ["intake", "strategy", "draft", "approve", "proof"],
        "deliverables_ar": ["خطة حملة", "نموذج حقول", "مسودات متابعة"],
        "pricing_range_sar": {"min": 2000, "max": 7500},
        "risk_level": "low",
        "required_integrations": ["linkedin_lead_forms"],
        "approval_policy": "no_auto_dm",
        "proof_metrics": ["leads_from_form", "followup_drafts"],
        "upgrade_path": "growth_os",
    },
    {
        "service_id": "meeting_booking_sprint",
        "name_ar": "سباق حجز اجتماعات",
        "target_customer_ar": "فرق لديها prospects بدون تحويل لاجتماعات",
        "outcome_ar": "دعوات + مسودة تقويم + أجندة + متابعة — بدون insert حي بدون موافقة.",
        "inputs_required": ["targets", "offer"],
        "workflow_steps": ["intake", "draft", "approve", "track", "proof"],
        "deliverables_ar": ["مسودات دعوة", "payload تقويم draft", "ملخص اجتماع"],
        "pricing_range_sar": {"min": 1500, "max": 5000},
        "risk_level": "low",
        "required_integrations": ["google_calendar"],
        "approval_policy": "calendar_insert_requires_approval",
        "proof_metrics": ["meetings_booked", "followups_sent_after_approval"],
        "upgrade_path": "growth_os",
    },
    {
        "service_id": "local_growth_os",
        "name_ar": "نمو محلي",
        "target_customer_ar": "عيادات ومطاعم ومتاجر",
        "outcome_ar": "تقييمات + واتساب inbound + روابط دفع draft.",
        "inputs_required": ["vertical", "branches"],
        "workflow_steps": ["intake", "strategy", "draft", "approve", "proof"],
        "deliverables_ar": ["كروت سمعة", "مسودات رد تقييم", "روابط دفع draft"],
        "pricing_range_sar": {"min": 999, "max": 2999},
        "risk_level": "medium",
        "required_integrations": ["google_business_profile", "whatsapp", "moyasar"],
        "approval_policy": "approval_required_for_send",
        "proof_metrics": ["reviews_addressed", "reactivation_drafts"],
        "upgrade_path": "growth_os",
    },
    {
        "service_id": "executive_growth_brief",
        "name_ar": "موجز تنفيذي يومي",
        "target_customer_ar": "CEO / مدير نمو",
        "outcome_ar": "٣ قرارات + ٣ فرص + ٣ مخاطر — عربي وأزرار ≤٣.",
        "inputs_required": ["company_profile"],
        "workflow_steps": ["intake", "analyze", "proof"],
        "deliverables_ar": ["موجز يومي", "تقرير نهاية يوم"],
        "pricing_range_sar": {"min": 499, "max": 999},
        "risk_level": "low",
        "required_integrations": [],
        "approval_policy": "suggest_and_draft_only",
        "proof_metrics": ["decisions_logged", "risks_flagged"],
        "upgrade_path": "growth_os",
    },
]


def list_tower_services() -> dict[str, Any]:
    return {"services": list(_SERVICES), "count": len(_SERVICES), "version": 1, "demo": True}


def list_service_ids() -> list[str]:
    return [s["service_id"] for s in _SERVICES]


def get_service_by_id(service_id: str) -> dict[str, Any] | None:
    sid = (service_id or "").strip().lower()
    for s in _SERVICES:
        if s["service_id"] == sid:
            return dict(s)
    return None
